Add another dbms to the project
BrizaMel/MAC0332 pull request #34
Opened 2023-11-24 21:11 UTC by lorenzoberts

2023-11-28 23:02 UTC, BrizaMel requested changes
Deixei algumas sugestoes

2023-11-28 23:02 UTC, BrizaMel commented on search-service/src/postgres/mod.rs
> -    pub async fn return_result(&self) -> &str {
🙌

2023-11-28 23:02 UTC, BrizaMel commented on search-service/src/database_storage/mod.rs
> +				.expect("Error retireving Database Schema Information")
nesse expect seria bom colocar de qual database se trata

2023-11-28 23:02 UTC, BrizaMel commented on search-service/src/database_storage/mod.rs
> +		let dbsm_to_connect = std::env::var("DMBS").unwrap_or_else(|_| panic!("DBMS variable missing in the environment"));
aqui seria melhor um expect do que um panic!, ou colocar um database padrão (Ex: postgres)

2023-11-29 02:41 UTC, lorenzoberts commented on search-service/src/database_storage/mod.rs
> +				.expect("Error retireving Database Schema Information")
fiz isso no commit 018f67675f175aa26013633dacb41471752f53b3

2023-11-29 02:52 UTC, BrizaMel approved these changes

2023-11-29 02:53 UTC, merged